
general:
  productiveBranch: 'master'


steps:
  executeMaven:
    globalSettingsFile: ''
    projectSettingsFile : ''

  deployToCfWithCli:
    smokeTestStatusCode: '200'


stages:
  staticCodeChecks:
    findbugsExcludesFile: '' #Path to findbugs exclude file
    pmdExcludes: '' # List or ANT style patterns
